# This is a basic workflow to help you get started with Actions

name: baseline-oss-fhir-prox

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:
  # This workflow contains a single job called "build"
  deploy-infra:
    runs-on: ubuntu-latest
    environment: sample
    outputs:
      fhir-name: ${{ steps.get-fhir-name.outputs.fhirName }} # output the fhirName to other jobs

    steps:

      # checkout 
    - uses: actions/checkout@v3

      # Log into Azure
    - name: az-login
      uses: Azure/login@v1.4.6
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      # Hash the resource group's ID so it's unique but also repeatable
      # steps: 
      # 1. retrieve the resouceGroup's id property
      # 2. hash the id and take the first 8 chars of the hash
      # 3. set the output using the hash substring
    - name: generate unique suffix 
      id: get-suffix
      shell: bash
      run: |
        rsGroupId=$(az group list --query "[?name=='${{ secrets.AZURE_RG }}'].id" -o tsv)
        suffix=$(echo -n $rsGroupId | shasum | cut -c1-8)
        echo "::set-output name=uniqueSuffix::$suffix"
        unset rsGroupId
        unset suffix
               
      # generate fcnAppName based on pefcn+suffix 
    - name: generate fhir name
      id: get-fhir-name
      shell: bash
      run: |
        fhirName="bcfhir${{steps.get-suffix.outputs.uniqueSuffix}}"
        echo "::set-output name=fhirName::$fhirName"
      
      # Deploy Bicep file
    - name: deploy-fhir
      uses: azure/arm-deploy@v1.0.8
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: 'workspaceName=ws${{steps.get-suffix.outputs.uniqueSuffix}}  fhirName=fhir${{steps.get-suffix.outputs.uniqueSuffix}}' 
        failOnStdErr: false